Week 2
DpAkyJ1A/scala-course-2022-spring pull request #3
Opened 2022-05-24 16:48 UTC by DpAkyJ1A

2022-05-24 21:59 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/and/three/quarters/homework/adt.scala
> +        case ErrorOr.Success(v)         => try if p(v) then ErrorOr.Success(v) else ErrorOr.Fail(NullPointerException("Bruh..")) catch{
`ErrorOr.Fail(NullPointerException("Bruh.."))` it's a really tricky case what we should return in case of a false predicate.
Generally I wanted to highlight that not all "boxes" could have `withFilter`. For example, `Future` do not have this method due to such unclearness  of what to return.

2022-05-24 22:01 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/and/three/quarters/homework/adt.scala
> +        case ErrorOr.Success(v) => try f(v) catch{
In this case you should just call `f(v)`. Returning `e` is useless. So if `foreach` fails with an exception then let's keep it as is.
Conclusion: remove `try-catch`.

2022-05-24 22:02 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/and/three/quarters/homework/adt.scala
> +      else ErrorOr.Fail(NullPointerException("Bruh..."))
I believe that `t` already contains an error in this case. Please use the original error from `t`.

2022-05-24 22:03 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/and/three/quarters/homework/adt.scala
> +      if t.isSuccess then ErrorOr.Success(t.get)
I'd prefer `pattern-matching` instead of `if` in this case.

2022-05-24 22:03 UTC, IgorWolkov requested changes
Added some comments.

2022-05-24 22:12 UTC, IgorWolkov requested changes
Btw, I haven't found a changes in `program` file. 
You should implement a tricky part in `program`.

2022-05-25 18:44 UTC, DpAkyJ1A commented on src/main/scala/karazin/scala/users/group/week2/and/three/quarters/homework/adt.scala
> +      if t.isSuccess then ErrorOr.Success(t.get)
![image](https://user-images.githubusercontent.com/101462237/170344768-cd3f83a5-8f22-43fb-98cc-2940b9dd95fc.png)
Also i have no idea why this is not working...

2022-05-25 22:41 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/and/three/quarters/homework/adt.scala
> +        case ErrorOr.Success(v)         => try if p(v) then ErrorOr.Success(v) else ErrorOr.Fail(NullPointerException("Bruh..")) catch{
It means that for such of "boxes" this method is useless. You shouldn't do anything.

2022-05-25 22:42 UTC, IgorWolkov approved these changes
Good job. Congrats!

2022-05-26 07:58 UTC, merged